package iconfont

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import java.io.File
import java.util.Locale

@CacheableTask
abstract class GenerateIconFontTask : DefaultTask() {
    @get:InputDirectory
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val inputDir: DirectoryProperty

    @get:OutputFile
    abstract val fontOutputFile: RegularFileProperty

    @get:OutputFile
    abstract val kotlinOutputFile: RegularFileProperty

    @get:Input
    abstract val codepointStart: Property<Int>

    @get:Input
    abstract val fontName: Property<String>

    @get:Input
    abstract val fontStyle: Property<String>

    @get:Input
    abstract val kotlinPackage: Property<String>

    @get:Input
    abstract val enumClassName: Property<String>

    init {
        description = "Generates an OpenType icon font from SVG files"
        group = "build"
        codepointStart.convention(0xE001)
        fontName.convention("CM Icons")
        fontStyle.convention("Regular")
        kotlinPackage.convention("az.theternal.cmplayground")
        enumClassName.convention("IconData")
    }

    @TaskAction
    fun generate() {
        val iconsDir = inputDir.get().asFile
        val svgFiles = collectSvgFiles(iconsDir)
        val generator = IconFontGenerator()
        val result = generator.generate(
            fontName = fontName.get(),
            fontStyle = fontStyle.get(),
            svgFiles = svgFiles,
            codePointStart = codepointStart.get()
        )
        val fontFile = fontOutputFile.get().asFile
        fontFile.parentFile?.mkdirs()
        fontFile.writeBytes(result.bytes)

        val kotlinFile = kotlinOutputFile.get().asFile
        writeKotlinEnum(
            output = kotlinFile,
            packageName = kotlinPackage.get(),
            enumName = enumClassName.get(),
            glyphs = result.generatedGlyphs
        )

        if (result.generatedGlyphs.isEmpty()) {
            logger.lifecycle("Generated icon font '${fontName.get()}' contains only the .notdef glyph (no SVG icons found).")
        } else {
            logger.lifecycle("Generated icon font '${fontName.get()}' with ${result.generatedGlyphs.size} glyphs:")
            result.generatedGlyphs.forEach { glyph ->
                logger.lifecycle("  • ${glyph.displayName} -> U+${glyph.codePoint.toString(16).uppercase()} (glyph #${glyph.glyphIndex})")
            }
        }
    }

    private fun collectSvgFiles(dir: File): List<File> {
        if (!dir.exists()) {
            logger.warn("Icon directory '${dir.absolutePath}' does not exist. Generating font with only the .notdef glyph.")
            return emptyList()
        }
        return dir.walkTopDown()
            .filter { it.isFile && it.extension.equals("svg", ignoreCase = true) }
            .sortedBy { it.relativeTo(dir).path }
            .toList()
    }

    private fun writeKotlinEnum(
        output: File,
        packageName: String,
        enumName: String,
        glyphs: List<GeneratedGlyph>
    ) {
        output.parentFile?.mkdirs()
        val builder = StringBuilder()
        builder.appendLine("// Auto-generated by GenerateIconFontTask; do not edit manually.")
        builder.appendLine("package $packageName")
        builder.appendLine()
        builder.appendLine("enum class $enumName(val code: Int) {")
        if (glyphs.isNotEmpty()) {
            glyphs.forEach { glyph ->
                val enumEntry = enumEntryName(glyph.name)
                val hexCode = "0x" + glyph.codePoint.toString(16).uppercase()
                builder.appendLine("    $enumEntry($hexCode),")
            }
        }
        builder.appendLine("    ;")
        builder.appendLine()
        builder.appendLine("    val value: String")
        builder.appendLine("        get() = Char(code).toString()")
        builder.appendLine("}")
        output.writeText(builder.toString())
    }

    private fun enumEntryName(baseName: String): String {
        if (baseName.isEmpty()) return "ICON"
        var candidate = baseName.uppercase(Locale.ROOT)
        if (!candidate.first().isLetter() && candidate.first() != '_') {
            candidate = "_${candidate}"
        }
        return candidate
    }
}
